### ISSUE TITLE
Intel Iris 550 Failure

### ISSUE THREAD

**Issue by sleepyspider1** [SaschaWillems/OpenCLCapsViewer#11]
Error: Could not read devices for the current platform!

Tried to run with the argument "-log" or just "log" with no quotes, but it did not give me a log.txt file.
The driver I have installed should have OpenCL 3.0 support.

Windows 10 21H2

Driver:
Intel Corporation
07-19-2022
31.0.101.2111

**Comment by sleepyspider1** [comment]
To be more specific, it's a Mac Book Pro Late 2016 with Bootcamp/Windows 10 installed and an Intel Iris 550 GPU.

**Comment by SaschaWillems** [comment]
That errors can occur if no OpenCL capable devices are found using `clGetDeviceID`. Do you have any other OpenCL application to test?

**Comment by ValZapod** [comment]
@SaschaWillems BTW, are you going tonsupport Metal, which is extension of OpenClL, GL, and stuff?

**Comment by SaschaWillems** [comment]
No, I don't plan to support Metal.

**Comment by sleepyspider1** [comment]
Just tested. Seems okay now.
Correctly reports OpenCL 3.0 NEO.
31.0.101.2114
[opencl.gpuinfo.org/displayreport.php?id=809](opencl.gpuinfo.org/displayreport.php?id=809)
