### ISSUE TITLE
Missing display of SVM capabilities for OpenCL 3.0 devices

### ISSUE THREAD

**Issue by bashbaug** [SaschaWillems/OpenCLCapsViewer#12]
**Describe the bug**
Missing display of SVM capabilities for OpenCL 3.0 devices

The caps viewer client doesn't seem to query and display SVM capabilities (see [CL_DEVICE_SVM_CAPABILITIES](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_SVM_CAPABILITIES)) for OpenCL 3.0 devices.  This also has the side effect that the only devices in [the database for CL_DEVICE_SVM_CAPABILITIES](https://opencl.gpuinfo.org/displaydeviceinfo.php?name=CL_DEVICE_SVM_CAPABILITIES) are OpenCL 2.x devices.

**Expected behavior**
The caps viewer client should query and display SVM capabilities for all OpenCL 2.0 and newer devices, not just for OpenCL 2.x devices.

**Screenshots**
N/A

**Platform (please complete the following information):**
Tested on two OpenCL 3.0 devices:

NVIDIA GPU:
 - Device: NVIDIA GeForce GTX 1060 6GB
 - OS: Windows 10
 - Driver version: 516.94

Intel CPU:
 - Device: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
 - OS: Windows 10
 - Driver version: 2021.13.11.0.23_160000

**Additional context**
The fix may be as simple as changing this check:
https://github.com/SaschaWillems/OpenCLCapsViewer/blob/master/deviceinfo.cpp#L560

from:

```c
if (clVersionMajor == 2)
```

to:

```c
if (clVersionMajor >= 2)
```

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. I just checked this with a CL 3.0 and on my device I do get a value for SVM capabilities.

But I'm not sure for the other OpenCL caps that would also be read when changing the if-statement you linked.

But what I could do, is also read SVM capabilities in the CL 3.0 if-block.

**Comment by bashbaug** [comment]
Since we didn't remove any queries in OpenCL 3.0 all of the "OpenCL 2.0" queries should be valid on a 3.0 device even if the features aren't supported.

The [Backwards Compatibility Appendix](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#opencl-3.0-backwards-compatibility) describes how many queries behave when an optional feature is not supported.  I just checked and all of the current "OpenCL 2.0" queries are described in this appendix except for the three preferred atomic alignment queries, which should debatably be listed in the "Shared Virtual Memory" section - we can fix this if it would be helpful.

Note, we also have a CTS test to verify this behavior:
https://github.com/KhronosGroup/OpenCL-CTS/blob/main/test_conformance/api/test_api_consistency.cpp

**Comment by bashbaug** [comment]
I added a PR that fixes this issue, in case it's helpful.  I've successfully tested it on both Intel and non-Intel OpenCL 3.0 implementations.  Thanks!
