### ISSUE TITLE
"Could not read devices for the platform" with Intel oneAPI Altera driver 

### ISSUE THREAD

**Issue by StefanG3D** [SaschaWillems/OpenCLCapsViewer#17]
How to reproduce:
Download [Intel oneAPI Base Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html) for Windows
Install all components
Check registry
`[HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors]
"C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\latest\\windows\\lib\\x64\\intelocl64.dll"=dword:00000000
"C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\latest\\windows\\lib\\x64\\intelocl64_emu.dll"=dword:00000000
"C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\latest\\windows\\lib\\oclfpga\\windows64\\bin\\alteracl.dll"=dword:00000000`
Start OpenCLCapsViewer, error message "Could not read devices for the platform" pops up

The culprit is alteracl.dll (which i never wanted or needed).

Workaround:
disable driver in registry by setting value=1
`"C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\latest\\windows\\lib\\oclfpga\\windows64\\bin\\alteracl.dll"=dword:00000001
`

**Comment by SaschaWillems** [comment]
So is this a bug that should be fixed in the application or in the Intel oneAPI Base Toolkit?

**Comment by StefanG3D** [comment]
I double-checked with [Indigo benchmark](https://www.indigorenderer.com/download-indigo-renderer)
It also fails to start with alteracl enabled.

I guess that means the fix has to come from Intel?

**Comment by SaschaWillems** [comment]
Yes, there's probably nothing I can do about this on my side.
